on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - name: Configure my repository settings
        id: hello
        uses: richardkeit/repo-settings-action@main
